# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://funfwo.github.io/pytime_reverse/"

git_url = "https://github.com/funfwo/pytime_reverse/tree/master/"

def custom_doc_links(name): return None
